### ISSUE TITLE
Android Download

### ISSUE THREAD

**Issue by trinhvanhuy** [sdkcarlos/cordova-ourcodeworld-sftpplugin#2]
Hello everyone,
I have this issue when i try to download files from ftp server

java.io.IOException: InputStream is closed
client.downloadFile.error @ fileService.js:217
(anonymous function) @ ourcodeworldsftp.js:111
cordova.callbackFromNative @ cordova.js:295
processMessage @ cordova.js:1081
processMessages @ cordova.js:1104
pollOnce @ cordova.js:973
pollOnceFromOnlineEvent @ cordova.js:960

Anyone has the solution ?

many thanks

**Comment by sdkcarlos** [comment]
Hi @trinhvanhuy , does this error appears with all the files ?

The plugin has been worked properly since i use it. But this plugin is for SFTP , i don't know if you can use it to connect to FTP.

I have searched a little while and i found this : [Not able to connect to Secured Channel when doing SFTP with JSch](http://stackoverflow.com/questions/13057638/not-able-to-connect-to-secured-channel-when-doing-sftp-with-jsch)

Could you open the `OurCodeWorldSFTP.java` file in your plugin and make the change as said in the post 

As your error appears in the Download action, make the change in the lines [[131 - 134]](https://github.com/sdkcarlos/cordova-ourcodeworld-sftpplugin/blob/master/src/android/OurCodeWorldSFTP.java#L131)

``` java
// Change in every action
Channel channel = session.openChannel("sftp");
channel.connect();

ChannelSftp sftp = (ChannelSftp) channel;
// For 
Channel channel = session.openChannel("sftp");
ChannelSftp sftp = (ChannelSftp) channel;
sftp.connect();
```

Actually the plugin connects before cast the variable as a SFTP Client, but it works normally so may be due to your FTP connection.

**Comment by trinhvanhuy** [comment]
Thanks so much @sdkcarlos 
But i've made its works yesterday 
I will close this issue
Have a nice day !
