### ISSUE TITLE
How can i create folder remotely 

### ISSUE THREAD

**Issue by sabirali007** [sdkcarlos/cordova-ourcodeworld-sftpplugin#4]
can we create folder on sFTP server remotely? if yes then how ?

**Comment by sdkcarlos** [comment]
Nope, currently this function is not available, but I'll implement it today.

**Comment by sdkcarlos** [comment]
Now since 0.5.1 you can create and delete a remote folder using the [createFolder](http://docs.ourcodeworld.com/projects/cordova-our-code-world-sftp-plugin/documentation/getting-started/using-the-sftp-client#createfolder) and [removeFolder](http://docs.ourcodeworld.com/projects/cordova-our-code-world-sftp-plugin/documentation/getting-started/using-the-sftp-client#removefolder) respectively. [Read the docs for more information](http://docs.ourcodeworld.com/projects/cordova-our-code-world-sftp-plugin/documentation/getting-started/using-the-sftp-client).

Just remove the plugin from your project and install it again.

**Comment by sabirali007** [comment]
Thanks sdkcarlos :)
